import Greeting from './greeting.component';
import Arrow from './arrow.component';
import SimpleState from './simplestate.component';
import Api from './api.component';
import Form from './form.component';
import Modal from './modal.component';
import Error from './error.component';
import Navbar from './navbar.component';
import Person from './person.component';
import Home from './home.component';
export {Greeting, Arrow, SimpleState, Api, Form, Modal, Error, Navbar, Person, Home};